# Config file
# Please read the README.md file for an introduction to this config file

# If you want to evaluate your own dataset you can change the path to the images. unfortunatly 
# you will have to build your own Evaluation script specific to your data
Dataset = "MSCO" # Name of the dataset you are using, this is to name data that is saved

[Paths]
pathToImages = "Resources/MSCOImages/*.jpg" # Path to all images that are evaluated use * like with glob. ASSR only used Test images for fair comparison since we dont need training
pathToMSCO = "Resources/MSCO.json" # Only needed when running evaluation for MSCO Dataset.
pathToASSR = "Resources/ASSR/" # Only needed if running Evaluation for the ASSR Dataset* is evaluated to anything with glob

[DeepGaze]
amountOfFixations = 10  # Amount of fixations per viewpath
amountOfViewPaths = 3   # DeepGaze generates 3 viewpaths with <amountOfFixations> fixations each

[SAM]
maxAmountOfMasks = 0 # 0 Means no limit. MSCO evaluated without a limit. ASSR uses a limit of 5 masks per image.

[Evaluation]
imagesPerChunk = 256 # In Evaluation images and masks are loaded and stored in memory depending on the amount of memory in your system you can adapt this number
